Delioos
AltierCapital/website pull request #1
Opened 2024-01-30 21:04 UTC by Delioos

# new sections
add of : 
- portfolio
- about
- altier projects
- "footer"

# issue
About section lack a bit of reactivity (planet size / padding issues). Also got an "valid" result on chrome but not ff.

2024-01-30 23:40 UTC, pnodet requested changes

2024-01-30 23:40 UTC, pnodet commented on src/app/(home)/page.tsx
@Delioos tu peux pas passer toute la page en client side, si ça marche c'est parce que le projet est pas sur la dernière version de next sinon il t'aurait crash une erreur. Il vaut mieux que tu passes en client juste le composant qui t'intéresse.

2024-01-30 23:40 UTC, pnodet commented on src/app/contact/page.tsx
> +      <script async src="https://tally.so/widgets/embed.js" />
à choisir, nextjs export un component `<Script />` qui est plus opti

2024-01-30 23:40 UTC, pnodet commented on src/components/ui/about/idea-presentation.tsx
> +export function Idea({ title, description, subDescription }): JSX.Element {
Interdit les props sans types haha

2024-01-30 23:40 UTC, pnodet commented on src/components/ui/projects/projects.tsx
> +      <Link href={"https://twitter.com/altitudexyz"}>
Le `Link` sert à rien quand tu envoies vers un autres site

2024-01-30 23:40 UTC, pnodet commented on src/components/layout/navbar.tsx
>        </li>
Est-ce que ça devrait pas être enlevé ça du coup ?

2024-01-30 23:40 UTC, pnodet commented on src/app/layout.tsx
> +    <body className="flex !h-[unset] min-h-screen flex-1 flex-col font-sans antialiased ">
```suggestion
    <body className="flex !h-[unset] min-h-screen flex-1 flex-col font-sans antialiased">
```

style nit

2024-01-30 23:40 UTC, pnodet commented on src/components/ui/folio/portfolio.tsx
> +    <div className="flex flex-wrap justify-center items-center gap-x-64 gap-y-10 md:gap-y-32 mt-10  ">
```suggestion
    <div className="flex flex-wrap justify-center items-center gap-x-64 gap-y-10 md:gap-y-32 mt-10">
```

style nit

2024-01-30 23:40 UTC, pnodet commented on src/components/ui/folio/portfolio.tsx
> +        href={"https://celestia.org/"}
```suggestion
        alt="celestia logo"
        href="https://celestia.org/"
```

2024-01-30 23:40 UTC, pnodet commented on src/components/ui/folio/portfolio.tsx
> +            className="w-20 md:w-36 "
```suggestion
            className="w-20 md:w-36"
```

2024-01-30 23:40 UTC, pnodet commented on src/components/ui/folio/portfolio.tsx
> +            alt={"eigen layer logo"}
```suggestion
            alt="eigen layer logo"
```

2024-01-30 23:40 UTC, pnodet commented on src/components/ui/folio/portfolio.tsx
> +        href={"https://www.mav.xyz/"}
```suggestion
        alt="maveric logo"
        href="https://www.mav.xyz/"
```

2024-01-30 23:40 UTC, pnodet commented on src/components/ui/about/planet-image.tsx
> +export const PlanetImage = ({ src, alt }) => (
```suggestion

type Props = {
	readonly src: string;
	readonly alt: string;
}

export const PlanetImage = ({ src, alt }: Props) => (
```

2024-01-30 23:40 UTC, pnodet commented on src/components/ui/about/about.tsx
> +      <div className="flex flex-row justify-between items-center px-20 md:space-x-40 ">
```suggestion
      <div className="flex flex-row justify-between items-center px-20 md:space-x-40">
```

2024-01-30 23:40 UTC, pnodet commented on src/components/ui/folio/project-image.tsx
> +export const ProjectImage = ({ src, alt, href }) => (
types des props

2024-01-30 23:40 UTC, pnodet commented on src/components/ui/footer.tsx
> +import Altier from "~/images/logo-sm.png";
```suggestion
import Image from "next/image";
import Altier from "~/images/logo-sm.png";
```

Supprimer les imports inutiles

2024-02-02 16:29 UTC, Delioos commented on src/components/layout/navbar.tsx
>        </li>
je sais pas ce que enki compte remplir des les sections avec les planètes donc j'avais pas touché, mais je peux l'enlever pour l'instant ça n'a pas trop ça place effectivement

2024-02-02 16:30 UTC, Delioos commented on src/components/layout/navbar.tsx
>        </li>
par contre j'ai l'impression que les éléments de la nav sont pas parfaitement centrés et je suis incapable de dire à quoi c'est dû

2024-02-03 01:13 UTC, pnodet commented on src/components/layout/navbar.tsx
>        </li>
C'est parce que le logo à gauche prend plus de place que les icons social à mon avis

2024-02-06 15:40 UTC, merged